[package]
name = "nexo-devmgr"
description = "Gerenciador de dispositivos: enumera PCI, deriva concessoes por dispositivo e inicia os drivers por IDs"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
nexo-sys.workspace = true
nexo-rt = { workspace = true, features = ["panic-handler"] }
nexo-proto.workspace = true
nexo-virtio.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
