[package]
name = "nexo-inputdev"
description = "Driver VirtIO-input (teclado/mouse paravirtualizado) em processo de usuario"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
nexo-sys.workspace = true
nexo-rt = { workspace = true, features = ["panic-handler"] }
nexo-proto.workspace = true
nexo-virtio.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
