[package]
name = "nexo-shell"
description = "Shell de diagnostico sobre a console VirtIO: info do sistema, arquivos via VFS, eco"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
nexo-sys.workspace = true
nexo-rt = { workspace = true, features = ["panic-handler"] }
nexo-proto.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
