[package]
name = "nexo-fs"
description = "Servidor de sistema de arquivos (NexoFS v0 sobre o driver de bloco) em processo de usuario"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
nexo-sys.workspace = true
nexo-rt = { workspace = true, features = ["panic-handler"] }
nexofs.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
