/* GERADO por tools/nexo-cheaders a partir de abi/syscall/src/lib.rs — nao edite. */
#ifndef NEXO_SYSCALLS_H
#define NEXO_SYSCALLS_H

#define NEXO_SYS_EXIT 0ULL
#define NEXO_SYS_LOG 1ULL
#define NEXO_SYS_TIME_NOW 2ULL
#define NEXO_SYS_YIELD 3ULL
#define NEXO_SYS_SLEEP 4ULL
#define NEXO_SYS_GET_PID 5ULL
#define NEXO_SYS_ABI_VERSION 6ULL
#define NEXO_SYS_DEBUG_INFO 7ULL
#define NEXO_SYS_HANDLE_CLOSE 8ULL
#define NEXO_SYS_HANDLE_DUPLICATE 9ULL
#define NEXO_SYS_CHANNEL_CREATE 10ULL
#define NEXO_SYS_CHANNEL_SEND 11ULL
#define NEXO_SYS_CHANNEL_RECV 12ULL
#define NEXO_SYS_HANDLE_INFO 13ULL
#define NEXO_SYS_PROCESS_SPAWN 14ULL
#define NEXO_SYS_PROCESS_WAIT 15ULL
#define NEXO_SYS_PROCESS_INFO 16ULL
#define NEXO_SYS_PCI_ENUM 17ULL
#define NEXO_SYS_PCI_CFG_READ 18ULL
#define NEXO_SYS_PCI_CFG_WRITE 19ULL
#define NEXO_SYS_MMIO_MAP 20ULL
#define NEXO_SYS_DMA_ALLOC 21ULL
#define NEXO_SYS_IRQ_ALLOC 22ULL
#define NEXO_SYS_IRQ_WAIT 23ULL
#define NEXO_SYS_DEVICE_OPEN 24ULL
#define NEXO_SYS_CHANNEL_TRY_RECV 25ULL
#define NEXO_SYS_CHANNEL_WAIT_ANY 26ULL
#define NEXO_SYS_MEMORY_CREATE 28ULL
#define NEXO_SYS_MEMORY_MAP 29ULL
#define NEXO_SYS_IRQ_CHANNEL 27ULL
#define NEXO_SYS_MEMORY_UNMAP 30ULL
#define NEXO_SYS_FB_INFO 31ULL
#define NEXO_SYS_PROCESS_SPAWN_MEM 32ULL
#define NEXO_SYS_TRACE 33ULL
#define NEXO_SYS_MAX 33ULL

#define NEXO_STATUS_OK 0ULL
#define NEXO_STATUS_INVALIDARGS 1ULL
#define NEXO_STATUS_BADADDRESS 2ULL
#define NEXO_STATUS_NOTSUPPORTED 3ULL
#define NEXO_STATUS_NOMEMORY 4ULL
#define NEXO_STATUS_NOTFOUND 5ULL
#define NEXO_STATUS_DENIED 6ULL
#define NEXO_STATUS_PEERCLOSED 7ULL
#define NEXO_STATUS_BADHANDLE 8ULL
#define NEXO_STATUS_WOULDBLOCK 9ULL
#define NEXO_STATUS_TOOBIG 10ULL
#define NEXO_STATUS_QUEUEFULL 11ULL
#define NEXO_STATUS_UNKNOWN 0xffffffffffffffffULL

#endif /* NEXO_SYSCALLS_H */
