[package]
name = "nexo-netd"
description = "Servico de rede residente: DHCP no arranque, sockets UDP/TCP nativos (nexo.sock) e DNS com cache sobre o driver netdev"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
nexo-sys.workspace = true
nexo-rt = { workspace = true, features = ["panic-handler"] }
nexo-proto.workspace = true
nexo-netstack.workspace = true

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
